### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by saadidrees711**

### CODE REVIEW

**Review by shahbaz-mehar — COMMENTED** [review]
Changes have been reviewed.

**Comment by emicha** [comment]
@saadidrees711 Could you add screenshots with "AltaPay" instead of "Valitor"?

**Comment by saadidrees711** [comment]
@shahbaz-mehar please review the updated images.

**Review by shahbaz-mehar — COMMENTED** [review]
Images changes have been reviewed.

**Comment by saadidrees711** [comment]
@emicha you may review the suggested changes.

**Review by emicha — APPROVED** [review]

**Pull request merged**
